[package]
name = "call-of-cthulhu"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
glob = "0.3.3"
image = "0.25.9"
lazy_static = "1.5.0"
notify-rust = "4.12.0"
png = "0.18.1"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
